# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
