# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobs.JobStatus'),
            preserve_default=False,
        ),
    ]
