# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='applicants',
        ),
    ]
