# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_jobpost_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
