# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20180113_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to='accounts.Profession'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to='jobs.JobStatus'),
        ),
    ]
