# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20180113_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(help_text='Enter as much detail about the job as possible', max_length=1000),
        ),
    ]
